### ISSUE TITLE
Stack overflow when printing values from (0..49004)

### ISSUE THREAD

**Issue by synecdoche** [danfuzz/samizdat#780]
SUMMARY
-------

I expect the following program to print the numbers 0 through 49004 inclusive:

```
for (x in (0..49004)) {
    note("\(x)")
};
```

STEPS TO REPRODUCE
-------------------

1. Put the code in the previous section in a file called `stackoverflow.sam`
2. Run: `samex --runtime=tot stackoverflow.sam`

EXPECTED RESULT
---------------

```
0
1
2
[...]
49002
49003
49004
```

ACTUAL RESULT
-------------

```
0
1
2
[...]
48997
48998
48999
49000
49001
49002
49003
Value stack overflow.
    at Cell.store on @<Cell @ 0x5a83e40>
    at anonymous instance of Closure
    at meta_If.loop on If
    at intBody (instance of Closure)
    at anonymous instance of Closure
    at intWithBase (instance of Closure)
    at Int_source (instance of Closure)
    at anonymous instance of Closure
    at meta_If.cases on If
    at anonymous instance of Closure
    at meta_If.or on If
    at sourceGeneral (instance of Closure)
    at anonymous instance of Closure
    at meta_If.cases on If
    at humanString (instance of Closure)
    at anonymous instance of Closure
    at meta_If.value on If
    at usual (instance of Closure)
    at anonymous instance of Closure
    at Generator_stdForEach (instance of Builtin)
    at ClosedRange.forEach on @<@<user class ClosedRange> @ 0x6131e70>
    at anonymous instance of Closure
    at meta_If.is on If
    at forEachAll (instance of Closure)
    at anonymous instance of Closure
    at anonymous instance of Closure
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at runProgram (instance of Closure)
    at runTextFile (instance of Closure)
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at anonymous instance of Closure
    at meta_If.is on If
    at runFile (instance of Closure)
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at anonymous instance of Closure
    at meta_If.cases on If
    at anonymous instance of Closure
    at runCommandLine (instance of Closure)
```

CONTEXT
-------

* Version: branch `master` as of 2e342f8e40eb958d298434fba4847dfe86d8b422
* OS: Linux Mint 17
* Compiler: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by danfuzz** [comment]
Thanks! I bet we're looking at a loop in the C code that needs to have a `datFrameReset()` (or the like) in it.

**Comment by danfuzz** [comment]
Fun times: I *cannot* yet repro on my laptop (OS X, Clang).

**Comment by danfuzz** [comment]
Reproducible now. Strangely enough, I get the exception when I hit 49006. I *thought* the entire codebase would be deterministic with respect to what landed on the value stack, but apparently not quite.

**Comment by danfuzz** [comment]
Pretty sure it's `Generator::stdCollect`, and it is unfortunately nontrivial:

Each iteration yields both a value to include in a collection *and* the next generator to use, with the previous generator becoming garbage. However, due to the — very simple — way that object lifetimes are managed in the C code, it's not easy to arrange for the system to tell that all those previous-generators are garbage. I don't think it's *impossible*, but it's going to be at least a little tricky.

Working on it! Thanks again!

**Comment by danfuzz** [comment]
BTW, I won't be able to make this work for arbitrarily large ranges, because the value stack will continue to have a fixed size and each generated value will still need to be on the stack while the `collect` is in-progress. What I'm hoping is that the limit on `collect` size will be `DAT_MAX_STACK - K` (where `K` is the base overhead) instead of `(DAT_MAX_STACK - K) / 2`.

`DAT_MAX_STACK` is currently set to be `100000`.

**Comment by danfuzz** [comment]
And also, I r dum: There are *two* loops in `Generator.c` that need work. I noticed `collect`, but of course you ran into the other one, `forEach`. With that one, I might be able to get it to work for arbitrarily large loop counts, as it doesn't need to collect anything.

**Comment by danfuzz** [comment]
Thanks again for filing the bug!
